# Generated by Django 6.0.7 on 2026-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['-es_portada', 'orden'], 'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de producto'},
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='es_portada',
            field=models.BooleanField(default=False, help_text='Imagen principal mostrada en el catálogo'),
        ),
    ]
