# Generated by Django 6.0.7 on 2026-07-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_imagenproducto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='direccion_local',
            field=models.CharField(blank=True, help_text='Dirección física de la tienda', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='foto_local',
            field=models.ImageField(blank=True, null=True, upload_to='local/'),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='mapa_url',
            field=models.URLField(blank=True, help_text='Link de Google Maps al local'),
        ),
    ]
