# Generated by Django 6.0.7 on 2026-07-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_configuracionnegocio_direccion_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='tipo_talla',
            field=models.CharField(choices=[('letra', 'Letra (XS, S, M, L, XL, XXL)'), ('brassiere', 'Brasier (Banda + Copa, ej: 75B)')], default='letra', help_text='Define qué sistema de tallas usan los productos de esta subcategoría', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.CharField(choices=[('Letra', [('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UNICA', 'Única')]), ('Brasier (Banda + Copa)', [('70A', '70A'), ('70B', '70B'), ('70C', '70C'), ('75A', '75A'), ('75B', '75B'), ('75C', '75C'), ('80A', '80A'), ('80B', '80B'), ('80C', '80C'), ('85A', '85A'), ('85B', '85B'), ('85C', '85C')])], default='UNICA', max_length=10),
        ),
    ]
