# Generated by Django 6.0.7 on 2026-08-02 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_subcategoria_tipo_talla_alter_producto_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionnegocio',
            name='monto_minimo_apartado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='agotado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('Letra', [('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UNICA', 'Única')]), ('Brasier (Banda + Copa)', [('70A', '70A'), ('70B', '70B'), ('70C', '70C'), ('75A', '75A'), ('75B', '75B'), ('75C', '75C'), ('80A', '80A'), ('80B', '80B'), ('80C', '80C'), ('85A', '85A'), ('85B', '85B'), ('85C', '85C')])], max_length=10)),
                ('color', models.CharField(blank=True, help_text='Déjalo vacío si el producto no maneja color', max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de producto',
                'ordering': ['talla', 'color'],
                'unique_together': {('producto', 'talla', 'color')},
            },
        ),
    ]
