# Generated by Django 6.0.7 on 2026-08-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_remove_configuracionnegocio_monto_minimo_apartado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='temporada',
            field=models.CharField(choices=[('todo_el_anio', 'Todo el año'), ('invierno', 'Invierno'), ('verano', 'Verano')], default='todo_el_anio', max_length=15),
        ),
    ]
