# Generated by Django 6.0.7 on 2026-08-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_producto_temporada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='varianteproducto',
            unique_together=set(),
        ),
    ]
