# Generated by Django 6.0.7 on 2026-07-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('qr', 'Pago con QR'), ('transferencia', 'Transferencia bancaria'), ('efectivo', 'Efectivo al recibir'), ('whatsapp', 'Coordinar por WhatsApp (pago presencial)')], max_length=15),
        ),
    ]
