# Generated by Django 6.0.7 on 2026-07-25 22:24

import pedidos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pago_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_estimada_entrega',
            field=models.DateField(blank=True, null=True, validators=[pedidos.models.validar_fecha_futura]),
        ),
    ]
