# Generated by Django 6.0.7 on 2026-08-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_fecha_estimada_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='monto_apartado',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='saldo_pendiente',
        ),
        migrations.AddField(
            model_name='pago',
            name='nombre_referencia',
            field=models.CharField(blank=True, help_text='Nombre con el que la clienta hizo el pago, para identificarlo manualmente', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('qr', 'Pago con QR'), ('efectivo', 'Efectivo (presencial)'), ('whatsapp', 'Coordinar por WhatsApp')], max_length=15),
        ),
    ]
