# Generated by Django 6.0.7 on 2026-08-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_pago_monto_apartado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
