# Generated by Django 6.0.7 on 2026-08-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_itempedido_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_verificacion', 'En verificación de pago'), ('confirmado', 'Confirmado'), ('preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='en_verificacion', max_length=20),
        ),
    ]
