# Generated by Django 6.0.7 on 2026-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('recogida', 'Recogida en punto físico'), ('tienda', 'Recogida en tienda física')], default='recogida', max_length=15),
        ),
    ]
