# Generated by Django 6.0.7 on 2026-08-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notificacion_entrega_pendiente',
            field=models.BooleanField(default=False, help_text="True cuando se marca como 'Entregado' y la clienta aún no ha visto el aviso"),
        ),
    ]
