# Generated by Django 6.0.7 on 2026-07-18 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_referencia', models.CharField(help_text='Ej: Casa, Trabajo', max_length=50)),
                ('calle', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=100)),
                ('referencias', models.TextField(blank=True, help_text='Puntos de referencia adicionales')),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección de entrega',
                'verbose_name_plural': 'Direcciones de entrega',
                'ordering': ['-es_predeterminada', '-creado'],
            },
        ),
    ]
