# Generated by Django 6.0.7 on 2026-07-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientas', '0002_direccionentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('mujer', 'Mujer'), ('hombre', 'Hombre'), ('otro', 'Otro / Prefiero no decir')], max_length=10),
        ),
    ]
