# Generated by Django 6.0.7 on 2026-08-03 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientas', '0003_perfilcliente_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_guardado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito guardado',
                'verbose_name_plural': 'Carritos guardados',
            },
        ),
    ]
