# Generated by Django 6.0.7 on 2026-07-25 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(choices=[('clienta', 'Clienta'), ('vendedora', 'Vendedora')], max_length=10)),
                ('texto', models.CharField(blank=True, max_length=1000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='chat/%Y/%m/')),
                ('automatico', models.BooleanField(default=False, help_text='Mensaje generado por el sistema (HU-19)')),
                ('leido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='La clienta dueña de esta conversación', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['creado'],
            },
        ),
    ]
