# Generated by Django 6.0.7 on 2026-08-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_imagenmensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenmensaje',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat/videos/%Y/%m/'),
        ),
    ]
