# Generated by Django 6.0.7 on 2026-08-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_imagenmensaje_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat/videos/%Y/%m/'),
        ),
    ]
